// flow-typed signature: 85744d2c4b76904dcf2eba12e66acec0
// flow-typed version: <<STUB>>/@types/react-copy-to-clipboard_v^4.2.6/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-copy-to-clipboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-copy-to-clipboard' {
  declare module.exports: any;
}
