// flow-typed signature: a9eaa155c3ffe0fba2e09534634f3cf8
// flow-typed version: <<STUB>>/cmz_v3.11.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cmz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cmz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cmz/bin/min' {
  declare module.exports: any;
}

declare module 'cmz/dist/cmz' {
  declare module.exports: any;
}

declare module 'cmz/dist/cmz.min' {
  declare module.exports: any;
}

declare module 'cmz/lib/index' {
  declare module.exports: any;
}

declare module 'cmz/lib/uniquify-name' {
  declare module.exports: any;
}

declare module 'cmz/lib/upsert-css' {
  declare module.exports: any;
}

declare module 'cmz/src/index' {
  declare module.exports: any;
}

declare module 'cmz/src/uniquify-name' {
  declare module.exports: any;
}

declare module 'cmz/src/upsert-css' {
  declare module.exports: any;
}

declare module 'cmz/tests/index' {
  declare module.exports: any;
}

declare module 'cmz/tests/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cmz/bin/min.js' {
  declare module.exports: $Exports<'cmz/bin/min'>;
}
declare module 'cmz/dist/cmz.js' {
  declare module.exports: $Exports<'cmz/dist/cmz'>;
}
declare module 'cmz/dist/cmz.min.js' {
  declare module.exports: $Exports<'cmz/dist/cmz.min'>;
}
declare module 'cmz/lib/index.js' {
  declare module.exports: $Exports<'cmz/lib/index'>;
}
declare module 'cmz/lib/uniquify-name.js' {
  declare module.exports: $Exports<'cmz/lib/uniquify-name'>;
}
declare module 'cmz/lib/upsert-css.js' {
  declare module.exports: $Exports<'cmz/lib/upsert-css'>;
}
declare module 'cmz/src/index.js' {
  declare module.exports: $Exports<'cmz/src/index'>;
}
declare module 'cmz/src/uniquify-name.js' {
  declare module.exports: $Exports<'cmz/src/uniquify-name'>;
}
declare module 'cmz/src/upsert-css.js' {
  declare module.exports: $Exports<'cmz/src/upsert-css'>;
}
declare module 'cmz/tests/index.js' {
  declare module.exports: $Exports<'cmz/tests/index'>;
}
declare module 'cmz/tests/usage.js' {
  declare module.exports: $Exports<'cmz/tests/usage'>;
}
