// flow-typed signature: 593b80b8e02169ce845930215573cb13
// flow-typed version: <<STUB>>/lodash.isnumber_v3.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isnumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isnumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isnumber/index' {
  declare module.exports: $Exports<'lodash.isnumber'>;
}
declare module 'lodash.isnumber/index.js' {
  declare module.exports: $Exports<'lodash.isnumber'>;
}
