// flow-typed signature: d7a50b82b3ac15920ea1b5f4941d7c3a
// flow-typed version: <<STUB>>/medium-editor_v5.23.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'medium-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'medium-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'medium-editor/demo/js/extension-table' {
  declare module.exports: any;
}

declare module 'medium-editor/dist/js/medium-editor' {
  declare module.exports: any;
}

declare module 'medium-editor/dist/js/medium-editor.min' {
  declare module.exports: any;
}

declare module 'medium-editor/Gruntfile' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/anchor-preview.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/anchor.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/auto-link.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/buttons.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/content.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/core-api.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/delay.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/drag-and-drop.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/dyn-elements.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/elements.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/events.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/exploits.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/extension.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/fontname.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/fontsize.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/full-content.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/header-tags.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/helpers/util' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/init.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/keyboard-commands.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/paste.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/placeholder.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/selection.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/serialize.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/setup.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/textarea.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/toolbar.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/util.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/vendor/jasmine-jsreporter-script' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/vendor/jasmine-jsreporter' {
  declare module.exports: any;
}

declare module 'medium-editor/spec/version.spec' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/core' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/defaults/buttons' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/defaults/options' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/events' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extension' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/anchor-preview' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/anchor' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/auto-link' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/button' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/deprecated/image-dragging' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/file-dragging' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/fontname' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/fontsize' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/form' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/keyboard-commands' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/paste' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/placeholder' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/extensions/toolbar' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/globals' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/polyfills' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/selection' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/util' {
  declare module.exports: any;
}

declare module 'medium-editor/src/js/version' {
  declare module.exports: any;
}

declare module 'medium-editor/src/wrappers/end' {
  declare module.exports: any;
}

declare module 'medium-editor/src/wrappers/start' {
  declare module.exports: any;
}

// Filename aliases
declare module 'medium-editor/demo/js/extension-table.js' {
  declare module.exports: $Exports<'medium-editor/demo/js/extension-table'>;
}
declare module 'medium-editor/dist/js/medium-editor.js' {
  declare module.exports: $Exports<'medium-editor/dist/js/medium-editor'>;
}
declare module 'medium-editor/dist/js/medium-editor.min.js' {
  declare module.exports: $Exports<'medium-editor/dist/js/medium-editor.min'>;
}
declare module 'medium-editor/Gruntfile.js' {
  declare module.exports: $Exports<'medium-editor/Gruntfile'>;
}
declare module 'medium-editor/index' {
  declare module.exports: $Exports<'medium-editor'>;
}
declare module 'medium-editor/index.js' {
  declare module.exports: $Exports<'medium-editor'>;
}
declare module 'medium-editor/spec/anchor-preview.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/anchor-preview.spec'>;
}
declare module 'medium-editor/spec/anchor.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/anchor.spec'>;
}
declare module 'medium-editor/spec/auto-link.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/auto-link.spec'>;
}
declare module 'medium-editor/spec/buttons.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/buttons.spec'>;
}
declare module 'medium-editor/spec/content.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/content.spec'>;
}
declare module 'medium-editor/spec/core-api.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/core-api.spec'>;
}
declare module 'medium-editor/spec/delay.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/delay.spec'>;
}
declare module 'medium-editor/spec/drag-and-drop.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/drag-and-drop.spec'>;
}
declare module 'medium-editor/spec/dyn-elements.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/dyn-elements.spec'>;
}
declare module 'medium-editor/spec/elements.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/elements.spec'>;
}
declare module 'medium-editor/spec/events.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/events.spec'>;
}
declare module 'medium-editor/spec/exploits.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/exploits.spec'>;
}
declare module 'medium-editor/spec/extension.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/extension.spec'>;
}
declare module 'medium-editor/spec/fontname.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/fontname.spec'>;
}
declare module 'medium-editor/spec/fontsize.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/fontsize.spec'>;
}
declare module 'medium-editor/spec/full-content.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/full-content.spec'>;
}
declare module 'medium-editor/spec/header-tags.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/header-tags.spec'>;
}
declare module 'medium-editor/spec/helpers/util.js' {
  declare module.exports: $Exports<'medium-editor/spec/helpers/util'>;
}
declare module 'medium-editor/spec/init.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/init.spec'>;
}
declare module 'medium-editor/spec/keyboard-commands.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/keyboard-commands.spec'>;
}
declare module 'medium-editor/spec/paste.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/paste.spec'>;
}
declare module 'medium-editor/spec/placeholder.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/placeholder.spec'>;
}
declare module 'medium-editor/spec/selection.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/selection.spec'>;
}
declare module 'medium-editor/spec/serialize.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/serialize.spec'>;
}
declare module 'medium-editor/spec/setup.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/setup.spec'>;
}
declare module 'medium-editor/spec/textarea.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/textarea.spec'>;
}
declare module 'medium-editor/spec/toolbar.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/toolbar.spec'>;
}
declare module 'medium-editor/spec/util.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/util.spec'>;
}
declare module 'medium-editor/spec/vendor/jasmine-jsreporter-script.js' {
  declare module.exports: $Exports<'medium-editor/spec/vendor/jasmine-jsreporter-script'>;
}
declare module 'medium-editor/spec/vendor/jasmine-jsreporter.js' {
  declare module.exports: $Exports<'medium-editor/spec/vendor/jasmine-jsreporter'>;
}
declare module 'medium-editor/spec/version.spec.js' {
  declare module.exports: $Exports<'medium-editor/spec/version.spec'>;
}
declare module 'medium-editor/src/js/core.js' {
  declare module.exports: $Exports<'medium-editor/src/js/core'>;
}
declare module 'medium-editor/src/js/defaults/buttons.js' {
  declare module.exports: $Exports<'medium-editor/src/js/defaults/buttons'>;
}
declare module 'medium-editor/src/js/defaults/options.js' {
  declare module.exports: $Exports<'medium-editor/src/js/defaults/options'>;
}
declare module 'medium-editor/src/js/events.js' {
  declare module.exports: $Exports<'medium-editor/src/js/events'>;
}
declare module 'medium-editor/src/js/extension.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extension'>;
}
declare module 'medium-editor/src/js/extensions/anchor-preview.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/anchor-preview'>;
}
declare module 'medium-editor/src/js/extensions/anchor.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/anchor'>;
}
declare module 'medium-editor/src/js/extensions/auto-link.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/auto-link'>;
}
declare module 'medium-editor/src/js/extensions/button.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/button'>;
}
declare module 'medium-editor/src/js/extensions/deprecated/image-dragging.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/deprecated/image-dragging'>;
}
declare module 'medium-editor/src/js/extensions/file-dragging.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/file-dragging'>;
}
declare module 'medium-editor/src/js/extensions/fontname.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/fontname'>;
}
declare module 'medium-editor/src/js/extensions/fontsize.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/fontsize'>;
}
declare module 'medium-editor/src/js/extensions/form.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/form'>;
}
declare module 'medium-editor/src/js/extensions/keyboard-commands.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/keyboard-commands'>;
}
declare module 'medium-editor/src/js/extensions/paste.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/paste'>;
}
declare module 'medium-editor/src/js/extensions/placeholder.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/placeholder'>;
}
declare module 'medium-editor/src/js/extensions/toolbar.js' {
  declare module.exports: $Exports<'medium-editor/src/js/extensions/toolbar'>;
}
declare module 'medium-editor/src/js/globals.js' {
  declare module.exports: $Exports<'medium-editor/src/js/globals'>;
}
declare module 'medium-editor/src/js/polyfills.js' {
  declare module.exports: $Exports<'medium-editor/src/js/polyfills'>;
}
declare module 'medium-editor/src/js/selection.js' {
  declare module.exports: $Exports<'medium-editor/src/js/selection'>;
}
declare module 'medium-editor/src/js/util.js' {
  declare module.exports: $Exports<'medium-editor/src/js/util'>;
}
declare module 'medium-editor/src/js/version.js' {
  declare module.exports: $Exports<'medium-editor/src/js/version'>;
}
declare module 'medium-editor/src/wrappers/end.js' {
  declare module.exports: $Exports<'medium-editor/src/wrappers/end'>;
}
declare module 'medium-editor/src/wrappers/start.js' {
  declare module.exports: $Exports<'medium-editor/src/wrappers/start'>;
}
