// flow-typed signature: f2e628e45425620fd07b3e416cff5449
// flow-typed version: <<STUB>>/react-data-grid-addons_v6.1.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-data-grid-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-data-grid-addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-data-grid-addons/dist/react-data-grid-addons' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/dist/react-data-grid-addons.min' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/__tests__/data/MockStateObject' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/__tests__/Grid.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/cells/headerCells/filters/__tests__/AutoCompleteFilter.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/cells/headerCells/filters/__tests__/NumericFilter.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/cells/headerCells/filters/AutoCompleteFilter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/cells/headerCells/filters/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/cells/headerCells/filters/MultiSelectFilter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/cells/headerCells/filters/NumericFilter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/cells/headerCells/filters/SingleSelectFilter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/__tests__/RowFilterer.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/__tests__/RowGrouper.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/__tests__/RowSorter.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/__tests__/Selectors.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/RowFilterer' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/RowGrouper' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/RowGrouperResolver' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/RowSorter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/data/Selectors' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable-header/__tests__/DraggableContainer.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable-header/__tests__/DraggableHeaderCell.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable-header/DraggableContainer' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable-header/DraggableHeaderCell' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable-header/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/__tests__/DragDropContainer.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/__tests__/DropTargetRowContainer.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/__tests__/RowActionsCell.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/__tests__/RowDragLayer.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/__tests__/TestDragSources' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/DragDropContainer' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/DraggableHeaderCell' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/DropTargetRowContainer' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/RowActionsCell' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/draggable/RowDragLayer' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/__tests__/AutoCompleteEditor-integration.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/__tests__/AutoCompleteEditor.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/__tests__/ContainerEditorWrapper.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/__tests__/DropDownEditor.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/AutoCompleteEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/AutoCompleteTokensEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/ContainerEditorWrapper' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/DateRangeEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/DropDownEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/editors/widgets/DateRangeFilter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/formatters/DateRangeFormatter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/formatters/DropDownFormatter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/formatters/ImageFormatter' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/formatters/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/menu/__tests__/ContextMenu.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/menu/__tests__/MenuHeader.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/menu/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/menu/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/menu/MenuHeader' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/performance/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/performance/SummaryItemModel' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/performance/SummaryParser' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/performance/whyDidYouUpdate' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/shared/html5DragDropContext' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/toolbars/AdvancedToolbar' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/toolbars/GroupedColumnButton' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/toolbars/GroupedColumnsPanel' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/toolbars/index' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/src/toolbars/Toolbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-data-grid-addons/dist/react-data-grid-addons.js' {
  declare module.exports: $Exports<'react-data-grid-addons/dist/react-data-grid-addons'>;
}
declare module 'react-data-grid-addons/dist/react-data-grid-addons.min.js' {
  declare module.exports: $Exports<'react-data-grid-addons/dist/react-data-grid-addons.min'>;
}
declare module 'react-data-grid-addons/index' {
  declare module.exports: $Exports<'react-data-grid-addons'>;
}
declare module 'react-data-grid-addons/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons'>;
}
declare module 'react-data-grid-addons/src/__tests__/data/MockStateObject.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/__tests__/data/MockStateObject'>;
}
declare module 'react-data-grid-addons/src/__tests__/Grid.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/__tests__/Grid.spec'>;
}
declare module 'react-data-grid-addons/src/cells/headerCells/filters/__tests__/AutoCompleteFilter.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/cells/headerCells/filters/__tests__/AutoCompleteFilter.spec'>;
}
declare module 'react-data-grid-addons/src/cells/headerCells/filters/__tests__/NumericFilter.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/cells/headerCells/filters/__tests__/NumericFilter.spec'>;
}
declare module 'react-data-grid-addons/src/cells/headerCells/filters/AutoCompleteFilter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/cells/headerCells/filters/AutoCompleteFilter'>;
}
declare module 'react-data-grid-addons/src/cells/headerCells/filters/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/cells/headerCells/filters/index'>;
}
declare module 'react-data-grid-addons/src/cells/headerCells/filters/MultiSelectFilter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/cells/headerCells/filters/MultiSelectFilter'>;
}
declare module 'react-data-grid-addons/src/cells/headerCells/filters/NumericFilter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/cells/headerCells/filters/NumericFilter'>;
}
declare module 'react-data-grid-addons/src/cells/headerCells/filters/SingleSelectFilter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/cells/headerCells/filters/SingleSelectFilter'>;
}
declare module 'react-data-grid-addons/src/data/__tests__/RowFilterer.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/__tests__/RowFilterer.spec'>;
}
declare module 'react-data-grid-addons/src/data/__tests__/RowGrouper.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/__tests__/RowGrouper.spec'>;
}
declare module 'react-data-grid-addons/src/data/__tests__/RowSorter.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/__tests__/RowSorter.spec'>;
}
declare module 'react-data-grid-addons/src/data/__tests__/Selectors.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/__tests__/Selectors.spec'>;
}
declare module 'react-data-grid-addons/src/data/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/index'>;
}
declare module 'react-data-grid-addons/src/data/RowFilterer.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/RowFilterer'>;
}
declare module 'react-data-grid-addons/src/data/RowGrouper.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/RowGrouper'>;
}
declare module 'react-data-grid-addons/src/data/RowGrouperResolver.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/RowGrouperResolver'>;
}
declare module 'react-data-grid-addons/src/data/RowSorter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/RowSorter'>;
}
declare module 'react-data-grid-addons/src/data/Selectors.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/data/Selectors'>;
}
declare module 'react-data-grid-addons/src/draggable-header/__tests__/DraggableContainer.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable-header/__tests__/DraggableContainer.spec'>;
}
declare module 'react-data-grid-addons/src/draggable-header/__tests__/DraggableHeaderCell.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable-header/__tests__/DraggableHeaderCell.spec'>;
}
declare module 'react-data-grid-addons/src/draggable-header/DraggableContainer.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable-header/DraggableContainer'>;
}
declare module 'react-data-grid-addons/src/draggable-header/DraggableHeaderCell.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable-header/DraggableHeaderCell'>;
}
declare module 'react-data-grid-addons/src/draggable-header/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable-header/index'>;
}
declare module 'react-data-grid-addons/src/draggable/__tests__/DragDropContainer.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/__tests__/DragDropContainer.spec'>;
}
declare module 'react-data-grid-addons/src/draggable/__tests__/DropTargetRowContainer.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/__tests__/DropTargetRowContainer.spec'>;
}
declare module 'react-data-grid-addons/src/draggable/__tests__/RowActionsCell.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/__tests__/RowActionsCell.spec'>;
}
declare module 'react-data-grid-addons/src/draggable/__tests__/RowDragLayer.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/__tests__/RowDragLayer.spec'>;
}
declare module 'react-data-grid-addons/src/draggable/__tests__/TestDragSources.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/__tests__/TestDragSources'>;
}
declare module 'react-data-grid-addons/src/draggable/DragDropContainer.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/DragDropContainer'>;
}
declare module 'react-data-grid-addons/src/draggable/DraggableHeaderCell.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/DraggableHeaderCell'>;
}
declare module 'react-data-grid-addons/src/draggable/DropTargetRowContainer.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/DropTargetRowContainer'>;
}
declare module 'react-data-grid-addons/src/draggable/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/index'>;
}
declare module 'react-data-grid-addons/src/draggable/RowActionsCell.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/RowActionsCell'>;
}
declare module 'react-data-grid-addons/src/draggable/RowDragLayer.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/draggable/RowDragLayer'>;
}
declare module 'react-data-grid-addons/src/editors/__tests__/AutoCompleteEditor-integration.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/__tests__/AutoCompleteEditor-integration.spec'>;
}
declare module 'react-data-grid-addons/src/editors/__tests__/AutoCompleteEditor.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/__tests__/AutoCompleteEditor.spec'>;
}
declare module 'react-data-grid-addons/src/editors/__tests__/ContainerEditorWrapper.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/__tests__/ContainerEditorWrapper.spec'>;
}
declare module 'react-data-grid-addons/src/editors/__tests__/DropDownEditor.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/__tests__/DropDownEditor.spec'>;
}
declare module 'react-data-grid-addons/src/editors/AutoCompleteEditor.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/AutoCompleteEditor'>;
}
declare module 'react-data-grid-addons/src/editors/AutoCompleteTokensEditor.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/AutoCompleteTokensEditor'>;
}
declare module 'react-data-grid-addons/src/editors/ContainerEditorWrapper.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/ContainerEditorWrapper'>;
}
declare module 'react-data-grid-addons/src/editors/DateRangeEditor.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/DateRangeEditor'>;
}
declare module 'react-data-grid-addons/src/editors/DropDownEditor.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/DropDownEditor'>;
}
declare module 'react-data-grid-addons/src/editors/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/index'>;
}
declare module 'react-data-grid-addons/src/editors/widgets/DateRangeFilter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/editors/widgets/DateRangeFilter'>;
}
declare module 'react-data-grid-addons/src/formatters/DateRangeFormatter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/formatters/DateRangeFormatter'>;
}
declare module 'react-data-grid-addons/src/formatters/DropDownFormatter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/formatters/DropDownFormatter'>;
}
declare module 'react-data-grid-addons/src/formatters/ImageFormatter.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/formatters/ImageFormatter'>;
}
declare module 'react-data-grid-addons/src/formatters/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/formatters/index'>;
}
declare module 'react-data-grid-addons/src/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/index'>;
}
declare module 'react-data-grid-addons/src/menu/__tests__/ContextMenu.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/menu/__tests__/ContextMenu.spec'>;
}
declare module 'react-data-grid-addons/src/menu/__tests__/MenuHeader.spec.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/menu/__tests__/MenuHeader.spec'>;
}
declare module 'react-data-grid-addons/src/menu/ContextMenu.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/menu/ContextMenu'>;
}
declare module 'react-data-grid-addons/src/menu/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/menu/index'>;
}
declare module 'react-data-grid-addons/src/menu/MenuHeader.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/menu/MenuHeader'>;
}
declare module 'react-data-grid-addons/src/performance/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/performance/index'>;
}
declare module 'react-data-grid-addons/src/performance/SummaryItemModel.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/performance/SummaryItemModel'>;
}
declare module 'react-data-grid-addons/src/performance/SummaryParser.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/performance/SummaryParser'>;
}
declare module 'react-data-grid-addons/src/performance/whyDidYouUpdate.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/performance/whyDidYouUpdate'>;
}
declare module 'react-data-grid-addons/src/shared/html5DragDropContext.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/shared/html5DragDropContext'>;
}
declare module 'react-data-grid-addons/src/toolbars/AdvancedToolbar.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/toolbars/AdvancedToolbar'>;
}
declare module 'react-data-grid-addons/src/toolbars/GroupedColumnButton.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/toolbars/GroupedColumnButton'>;
}
declare module 'react-data-grid-addons/src/toolbars/GroupedColumnsPanel.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/toolbars/GroupedColumnsPanel'>;
}
declare module 'react-data-grid-addons/src/toolbars/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/toolbars/index'>;
}
declare module 'react-data-grid-addons/src/toolbars/Toolbar.js' {
  declare module.exports: $Exports<'react-data-grid-addons/src/toolbars/Toolbar'>;
}
