// flow-typed signature: 94f3946f5faa3b0c16238f9e2824e5e5
// flow-typed version: <<STUB>>/react-avatar_v3.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-avatar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-avatar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-avatar/es/cache' {
  declare module.exports: any;
}

declare module 'react-avatar/es/context' {
  declare module.exports: any;
}

declare module 'react-avatar/es/index' {
  declare module.exports: any;
}

declare module 'react-avatar/es/internal-state' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/AvatarRedirect' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Facebook' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Github' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Google' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Gravatar' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Icon' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Skype' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Src' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Twitter' {
  declare module.exports: any;
}

declare module 'react-avatar/es/sources/Value' {
  declare module.exports: any;
}

declare module 'react-avatar/es/utils' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/cache' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/context' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/index' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/internal-state' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/AvatarRedirect' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Facebook' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Github' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Google' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Gravatar' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Icon' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Skype' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Src' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Twitter' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Value' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-avatar/es/cache.js' {
  declare module.exports: $Exports<'react-avatar/es/cache'>;
}
declare module 'react-avatar/es/context.js' {
  declare module.exports: $Exports<'react-avatar/es/context'>;
}
declare module 'react-avatar/es/index.js' {
  declare module.exports: $Exports<'react-avatar/es/index'>;
}
declare module 'react-avatar/es/internal-state.js' {
  declare module.exports: $Exports<'react-avatar/es/internal-state'>;
}
declare module 'react-avatar/es/sources/AvatarRedirect.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/AvatarRedirect'>;
}
declare module 'react-avatar/es/sources/Facebook.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Facebook'>;
}
declare module 'react-avatar/es/sources/Github.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Github'>;
}
declare module 'react-avatar/es/sources/Google.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Google'>;
}
declare module 'react-avatar/es/sources/Gravatar.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Gravatar'>;
}
declare module 'react-avatar/es/sources/Icon.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Icon'>;
}
declare module 'react-avatar/es/sources/Skype.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Skype'>;
}
declare module 'react-avatar/es/sources/Src.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Src'>;
}
declare module 'react-avatar/es/sources/Twitter.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Twitter'>;
}
declare module 'react-avatar/es/sources/Value.js' {
  declare module.exports: $Exports<'react-avatar/es/sources/Value'>;
}
declare module 'react-avatar/es/utils.js' {
  declare module.exports: $Exports<'react-avatar/es/utils'>;
}
declare module 'react-avatar/lib/cache.js' {
  declare module.exports: $Exports<'react-avatar/lib/cache'>;
}
declare module 'react-avatar/lib/context.js' {
  declare module.exports: $Exports<'react-avatar/lib/context'>;
}
declare module 'react-avatar/lib/index.js' {
  declare module.exports: $Exports<'react-avatar/lib/index'>;
}
declare module 'react-avatar/lib/internal-state.js' {
  declare module.exports: $Exports<'react-avatar/lib/internal-state'>;
}
declare module 'react-avatar/lib/sources/AvatarRedirect.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/AvatarRedirect'>;
}
declare module 'react-avatar/lib/sources/Facebook.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Facebook'>;
}
declare module 'react-avatar/lib/sources/Github.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Github'>;
}
declare module 'react-avatar/lib/sources/Google.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Google'>;
}
declare module 'react-avatar/lib/sources/Gravatar.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Gravatar'>;
}
declare module 'react-avatar/lib/sources/Icon.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Icon'>;
}
declare module 'react-avatar/lib/sources/Skype.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Skype'>;
}
declare module 'react-avatar/lib/sources/Src.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Src'>;
}
declare module 'react-avatar/lib/sources/Twitter.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Twitter'>;
}
declare module 'react-avatar/lib/sources/Value.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Value'>;
}
declare module 'react-avatar/lib/utils.js' {
  declare module.exports: $Exports<'react-avatar/lib/utils'>;
}
