// flow-typed signature: 1f9f501431a9a33ce98588b344d818f5
// flow-typed version: <<STUB>>/react-truncate-markup_v4.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-truncate-markup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-truncate-markup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-truncate-markup/es/index' {
  declare module.exports: any;
}

declare module 'react-truncate-markup/es/tokenize-rules' {
  declare module.exports: any;
}

declare module 'react-truncate-markup/lib/index' {
  declare module.exports: any;
}

declare module 'react-truncate-markup/lib/tokenize-rules' {
  declare module.exports: any;
}

declare module 'react-truncate-markup/umd/react-truncate-markup' {
  declare module.exports: any;
}

declare module 'react-truncate-markup/umd/react-truncate-markup.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-truncate-markup/es/index.js' {
  declare module.exports: $Exports<'react-truncate-markup/es/index'>;
}
declare module 'react-truncate-markup/es/tokenize-rules.js' {
  declare module.exports: $Exports<'react-truncate-markup/es/tokenize-rules'>;
}
declare module 'react-truncate-markup/lib/index.js' {
  declare module.exports: $Exports<'react-truncate-markup/lib/index'>;
}
declare module 'react-truncate-markup/lib/tokenize-rules.js' {
  declare module.exports: $Exports<'react-truncate-markup/lib/tokenize-rules'>;
}
declare module 'react-truncate-markup/umd/react-truncate-markup.js' {
  declare module.exports: $Exports<'react-truncate-markup/umd/react-truncate-markup'>;
}
declare module 'react-truncate-markup/umd/react-truncate-markup.min.js' {
  declare module.exports: $Exports<'react-truncate-markup/umd/react-truncate-markup.min'>;
}
