// flow-typed signature: 43546bd329f67e43cc543b877e7c1cea
// flow-typed version: <<STUB>>/tui-editor_v1.2.10/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tui-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tui-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tui-editor/dist/tui-editor-Editor-all' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-Editor-all.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-Editor' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-Editor.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extChart' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extChart.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extColorSyntax' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extColorSyntax.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extScrollSync' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extScrollSync.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extTable' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extTable.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extUML' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-extUML.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-Viewer-all' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-Viewer-all.min' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-Viewer' {
  declare module.exports: any;
}

declare module 'tui-editor/dist/tui-editor-Viewer.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tui-editor/dist/tui-editor-Editor-all.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Editor-all'>;
}
declare module 'tui-editor/dist/tui-editor-Editor-all.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Editor-all.min'>;
}
declare module 'tui-editor/dist/tui-editor-Editor.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Editor'>;
}
declare module 'tui-editor/dist/tui-editor-Editor.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Editor.min'>;
}
declare module 'tui-editor/dist/tui-editor-extChart.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extChart'>;
}
declare module 'tui-editor/dist/tui-editor-extChart.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extChart.min'>;
}
declare module 'tui-editor/dist/tui-editor-extColorSyntax.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extColorSyntax'>;
}
declare module 'tui-editor/dist/tui-editor-extColorSyntax.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extColorSyntax.min'>;
}
declare module 'tui-editor/dist/tui-editor-extScrollSync.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extScrollSync'>;
}
declare module 'tui-editor/dist/tui-editor-extScrollSync.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extScrollSync.min'>;
}
declare module 'tui-editor/dist/tui-editor-extTable.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extTable'>;
}
declare module 'tui-editor/dist/tui-editor-extTable.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extTable.min'>;
}
declare module 'tui-editor/dist/tui-editor-extUML.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extUML'>;
}
declare module 'tui-editor/dist/tui-editor-extUML.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-extUML.min'>;
}
declare module 'tui-editor/dist/tui-editor-Viewer-all.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Viewer-all'>;
}
declare module 'tui-editor/dist/tui-editor-Viewer-all.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Viewer-all.min'>;
}
declare module 'tui-editor/dist/tui-editor-Viewer.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Viewer'>;
}
declare module 'tui-editor/dist/tui-editor-Viewer.min.js' {
  declare module.exports: $Exports<'tui-editor/dist/tui-editor-Viewer.min'>;
}

/*
* CSS Files
*/
declare module 'tui-editor/dist/tui-editor.css' {
  declare module.exports: any;
}
declare module 'tui-editor/dist/tui-editor-contents.css' {
  declare module.exports: any;
}
