// flow-typed signature: 5c466a22dc6bc3c83c8e9dd563152bc8
// flow-typed version: <<STUB>>/@storybook/addon-storyshots_v4.0.9/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-storyshots'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-storyshots' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-storyshots/dist/api/ensureOptionsDefaults' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/api/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/api/integrityTestTemplate' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/angular/app.component' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/angular/app.token' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/angular/helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/angular/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/angular/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/angular/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/configure' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/frameworkLoader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/hasDependency' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/html/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/html/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/react/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/react/renderShallowTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/react/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/riot/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/riot/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/rn/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/svelte/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/svelte/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/vue/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/frameworks/vue/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/Stories2SnapsConverter' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/Stories2SnapsConverter.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/test-bodies' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/api/ensureOptionsDefaults' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/api/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/api/integrityTestTemplate' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/api/snapshotsTestsTemplate' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/angular/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/angular/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/configure' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/frameworkLoader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/hasDependency' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/html/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/html/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/react/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/react/renderShallowTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/react/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/riot/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/riot/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/rn/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/svelte/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/svelte/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/vue/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/frameworks/vue/renderTree' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/Stories2SnapsConverter' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/Stories2SnapsConverter.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/src/test-bodies' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/directly_required/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/required_with_context/Async.stories' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/required_with_context/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/required_with_context/Welcome.stories' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.async.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.configFunc.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.enzyme.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.renderOnly.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.renderWithOptions.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.shallow.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.shallowWithOptions.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.snapshotWithOptionsFunction.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.specificConfig.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/storyshot.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-storyshots/dist/api/ensureOptionsDefaults.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/api/ensureOptionsDefaults'>;
}
declare module '@storybook/addon-storyshots/dist/api/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/api/index'>;
}
declare module '@storybook/addon-storyshots/dist/api/integrityTestTemplate.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/api/integrityTestTemplate'>;
}
declare module '@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/angular/app.component.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/angular/app.component'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/angular/app.token.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/angular/app.token'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/angular/helpers.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/angular/helpers'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/angular/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/angular/loader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/angular/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/angular/renderTree'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/angular/types.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/angular/types'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/configure.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/configure'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/frameworkLoader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/hasDependency.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/hasDependency'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/html/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/html/loader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/html/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/html/renderTree'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/react/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/react/loader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/react/renderShallowTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/react/renderShallowTree'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/react/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/react/renderTree'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/riot/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/riot/loader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/riot/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/riot/renderTree'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/rn/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/rn/loader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/svelte/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/svelte/loader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/svelte/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/svelte/renderTree'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/vue/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/vue/loader'>;
}
declare module '@storybook/addon-storyshots/dist/frameworks/vue/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/frameworks/vue/renderTree'>;
}
declare module '@storybook/addon-storyshots/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/index'>;
}
declare module '@storybook/addon-storyshots/dist/Stories2SnapsConverter.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/Stories2SnapsConverter'>;
}
declare module '@storybook/addon-storyshots/dist/Stories2SnapsConverter.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/Stories2SnapsConverter.test'>;
}
declare module '@storybook/addon-storyshots/dist/test-bodies.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/test-bodies'>;
}
declare module '@storybook/addon-storyshots/src/api/ensureOptionsDefaults.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/api/ensureOptionsDefaults'>;
}
declare module '@storybook/addon-storyshots/src/api/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/api/index'>;
}
declare module '@storybook/addon-storyshots/src/api/integrityTestTemplate.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/api/integrityTestTemplate'>;
}
declare module '@storybook/addon-storyshots/src/api/snapshotsTestsTemplate.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/api/snapshotsTestsTemplate'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/angular/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/angular/loader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/angular/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/angular/renderTree'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/configure.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/configure'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/frameworkLoader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/frameworkLoader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/hasDependency.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/hasDependency'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/html/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/html/loader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/html/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/html/renderTree'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/react/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/react/loader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/react/renderShallowTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/react/renderShallowTree'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/react/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/react/renderTree'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/riot/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/riot/loader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/riot/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/riot/renderTree'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/rn/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/rn/loader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/svelte/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/svelte/loader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/svelte/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/svelte/renderTree'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/vue/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/vue/loader'>;
}
declare module '@storybook/addon-storyshots/src/frameworks/vue/renderTree.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/frameworks/vue/renderTree'>;
}
declare module '@storybook/addon-storyshots/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/index'>;
}
declare module '@storybook/addon-storyshots/src/Stories2SnapsConverter.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/Stories2SnapsConverter'>;
}
declare module '@storybook/addon-storyshots/src/Stories2SnapsConverter.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/Stories2SnapsConverter.test'>;
}
declare module '@storybook/addon-storyshots/src/test-bodies.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/src/test-bodies'>;
}
declare module '@storybook/addon-storyshots/stories/directly_required/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/directly_required/index'>;
}
declare module '@storybook/addon-storyshots/stories/required_with_context/Async.stories.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/required_with_context/Async.stories'>;
}
declare module '@storybook/addon-storyshots/stories/required_with_context/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/required_with_context/Button.stories'>;
}
declare module '@storybook/addon-storyshots/stories/required_with_context/Welcome.stories.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/required_with_context/Welcome.stories'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.async.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.async.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.configFunc.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.configFunc.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.enzyme.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.enzyme.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.renderOnly.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.renderOnly.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.renderWithOptions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.renderWithOptions.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.shallow.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.shallow.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.shallowWithOptions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.shallowWithOptions.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.snapshotWithOptionsFunction.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.snapshotWithOptionsFunction.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.specificConfig.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.specificConfig.test'>;
}
declare module '@storybook/addon-storyshots/stories/storyshot.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/storyshot.test'>;
}
