// flow-typed signature: 7b70ee0976d7b71a13d3a26232cc9c2f
// flow-typed version: <<STUB>>/@storybook/addon-backgrounds_v4.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-backgrounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-backgrounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-backgrounds/dist/__tests__/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/__tests__/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/deprecated' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/mithril' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/__tests__/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/__tests__/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/deprecated' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-backgrounds/dist/__tests__/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/__tests__/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/dist/__tests__/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/__tests__/Swatch'>;
}
declare module '@storybook/addon-backgrounds/dist/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/constants'>;
}
declare module '@storybook/addon-backgrounds/dist/deprecated.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/deprecated'>;
}
declare module '@storybook/addon-backgrounds/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/index'>;
}
declare module '@storybook/addon-backgrounds/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/register'>;
}
declare module '@storybook/addon-backgrounds/dist/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/Swatch'>;
}
declare module '@storybook/addon-backgrounds/mithril.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/mithril'>;
}
declare module '@storybook/addon-backgrounds/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/register'>;
}
declare module '@storybook/addon-backgrounds/src/__tests__/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/__tests__/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/src/__tests__/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/__tests__/Swatch'>;
}
declare module '@storybook/addon-backgrounds/src/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/src/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/constants'>;
}
declare module '@storybook/addon-backgrounds/src/deprecated.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/deprecated'>;
}
declare module '@storybook/addon-backgrounds/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/index'>;
}
declare module '@storybook/addon-backgrounds/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/register'>;
}
declare module '@storybook/addon-backgrounds/src/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/Swatch'>;
}
declare module '@storybook/addon-backgrounds/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/vue'>;
}
