// flow-typed signature: 0fee605b3944e6724dcd6e1184aca712
// flow-typed version: <<STUB>>/@storybook/addon-viewport_v4.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-viewport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-viewport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-viewport/dist/manager/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/manager/components/tests/Panel.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/manager/components/tests/viewportInfo.spec' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/manager/components/viewportInfo' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/manager/tests/index.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/preview/tests/index.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/preview/withViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/shared/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/manager/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/manager/components/tests/Panel.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/manager/components/tests/viewportInfo.spec' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/manager/components/viewportInfo' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/manager/tests/index.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/preview/tests/index.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/preview/withViewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/src/shared/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-viewport/dist/manager/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/manager/components/Panel'>;
}
declare module '@storybook/addon-viewport/dist/manager/components/tests/Panel.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/manager/components/tests/Panel.test'>;
}
declare module '@storybook/addon-viewport/dist/manager/components/tests/viewportInfo.spec.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/manager/components/tests/viewportInfo.spec'>;
}
declare module '@storybook/addon-viewport/dist/manager/components/viewportInfo.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/manager/components/viewportInfo'>;
}
declare module '@storybook/addon-viewport/dist/manager/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/manager/index'>;
}
declare module '@storybook/addon-viewport/dist/manager/tests/index.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/manager/tests/index.test'>;
}
declare module '@storybook/addon-viewport/dist/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/preview/index'>;
}
declare module '@storybook/addon-viewport/dist/preview/tests/index.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/preview/tests/index.test'>;
}
declare module '@storybook/addon-viewport/dist/preview/withViewport.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/preview/withViewport'>;
}
declare module '@storybook/addon-viewport/dist/shared/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/shared/index'>;
}
declare module '@storybook/addon-viewport/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/manager'>;
}
declare module '@storybook/addon-viewport/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/preview'>;
}
declare module '@storybook/addon-viewport/register.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/register'>;
}
declare module '@storybook/addon-viewport/src/manager/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/manager/components/Panel'>;
}
declare module '@storybook/addon-viewport/src/manager/components/tests/Panel.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/manager/components/tests/Panel.test'>;
}
declare module '@storybook/addon-viewport/src/manager/components/tests/viewportInfo.spec.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/manager/components/tests/viewportInfo.spec'>;
}
declare module '@storybook/addon-viewport/src/manager/components/viewportInfo.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/manager/components/viewportInfo'>;
}
declare module '@storybook/addon-viewport/src/manager/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/manager/index'>;
}
declare module '@storybook/addon-viewport/src/manager/tests/index.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/manager/tests/index.test'>;
}
declare module '@storybook/addon-viewport/src/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/preview/index'>;
}
declare module '@storybook/addon-viewport/src/preview/tests/index.test.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/preview/tests/index.test'>;
}
declare module '@storybook/addon-viewport/src/preview/withViewport.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/preview/withViewport'>;
}
declare module '@storybook/addon-viewport/src/shared/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/src/shared/index'>;
}
